services:
  frontend:
    build:
      context: .
    container_name: doctors_booking_testing
    ports:
      - "8000:80"
    volumes:
      - ./doctors_booking/static:/home/www-data/app/static
      - ./doctors_booking/api:/home/www-data/app/api
      - ./doctors_booking/frontend:/home/www-data/app/frontend
      - ./doctors_booking/doctors_booking:/home/www-data/app/doctors_booking
      - ./doctors_booking/templates:/home/www-data/app/templates
    environment:
      - NAME='Room Booking' # Pretty Name
      - APPNAME=doctors_booking # Django project name. The folder name that contains the wsgi.py file.
      - PROJECTPATH=/home/www-data/app
      - PIDFILE=/tmp/gunicorn.pid
    restart: unless-stopped
